version: "3.8"
services:
  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/initialize_database.sql
  restapi:
    build:
      context: ./restapi
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - HOST=${HOST}
    ports:
      - "3000:3000"
  app:
    build:
      context: ./app
    depends_on:
      - restapi
    ports:
      - "4200:80"
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:9.3.1"
    depends_on:
      - app
    environment:
      - cypress_baseUrl=${BASE_URL}:${PORT}
    volumes:
      - ./app/cypress:/cypress
      - ./app/cypress.json:/cypress.json
volumes:
  db:
    driver: local
