CREATE DOMAIN phone_number AS TEXT CHECK(VALUE ~ '^\+(?:[0-9]\x20?){6,14}[0-9]$'); 
-- regex: https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s03.html

CREATE TABLE IF NOT EXISTS office (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street CHARACTER varying(255) NOT NULL,
    street_number CHARACTER varying(255) NOT NULL,
    postcode CHARACTER varying(255) NOT NULL,
    city CHARACTER varying(255) NOT NULL,
    country CHARACTER varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO office (street, street_number, postcode, city, country) VALUES 
('Lõõtsa', '1A', '11415', 'Tallinn', 'Estonia'), 
('Žalgirio', '96', '09300', 'Vilnius', 'Lithuania'), 
('Satekles', '2B', '1050', 'Riga', 'Latvia');

CREATE TABLE IF NOT EXISTS employee (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name CHARACTER varying(255) NOT NULL,
    last_name CHARACTER varying(255) NOT NULL,
    birth_date DATE NOT NULL,
    phone phone_number,
    tags TEXT[],
    office_id INT,
    CONSTRAINT fk_office FOREIGN KEY (office_id) REFERENCES office(id),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO employee (first_name, last_name, birth_date, phone, office_id, tags) VALUES
('Gerda', 'Maasing', CURRENT_DATE, '+37200000001', 1, '{"Junior Recruiter", "Office Administrator"}'), 
('Maria', 'Gendelevitch', CURRENT_DATE, '+37200000002', 1, '{"Senior HR Specialist"}'),
('Marta', 'Sedliņa', CURRENT_DATE, '+37100000001', 3, '{"HR Specialist"}'),
('Alina', 'Isajenko', CURRENT_DATE, '+37100000002', 3, '{"Senior HR Specialist"}'),
('Oleg', 'Karpušenko', CURRENT_DATE, '+37100000003', 3, '{"Head of HR"}');